modLoader="javafml"
loaderVersion="[26,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/happy-stats/issues"

[[mods]]
    modId="micromods"
    version="1.0"
    displayName="HappyStats"
	authors="ManApart"
    credits="Stats for Horses and other tweaks"
    description='''
    MicroMods - a collection of oddities too small for their own mods
    '''

[[dependencies.micromods]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"